In [2]:
import numpy as np

# Introduction to Linear Algebra with NumPy

## Conceptos básicos de álgebra lineal

- **Vectores**: Son objetos que tienen magnitud y dirección. Se pueden representar como una lista de números, que son las coordenadas del vector.
- **Matrices**: Son arreglos bidimensionales de números que representan transformaciones lineales. Una matriz puede transformar un vector en otro vector.
- **Transformaciones Lineales**: Son funciones que toman vectores como entrada y producen otros vectores como salida, respetando las operaciones de suma y multiplicación por un escalar.
- **Espacios Vectoriales**: Conjuntos de vectores que pueden sumarse entre sí y multiplicarse por escalares, siguiendo ciertas reglas.

## Ejemplos aplicativos

- **Gráficos por Computadora**: Las transformaciones lineales se utilizan para rotar, escalar y traducir objetos en la pantalla.
- **Procesamiento de Imágenes**: Las matrices de convolución (kernels) se usan para aplicar filtros a las imágenes, mejorando su calidad o destacando características específicas.
- **Aprendizaje Automático**: Los algoritmos de regresión lineal, redes neuronales y otros modelos dependen en gran medida de las operaciones matriciales.

## Main operations in Linear Algebra - using NumPy

### Matriz addition

The addition is made adding element by element. For example:

$$A = 
\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}$$

$$B = 
\begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}$$

The sum of $A$ with $B$ is:

$$A + B =
\begin{pmatrix}
1 + 5 & 2 + 6 \\
3 + 7 & 4 + 8
\end{pmatrix}
=
\begin{pmatrix}
6 & 8 \\
10 & 12
\end{pmatrix}
$$

In NumPy code:

In [3]:
# Import numpy if not imported yer
# import numpy as np

A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

C = A + B
print(f'A = \n{A}')
print(f'B = \n{B}')
print('\n')
print(f'A + B = \n{C}')

A = 
[[1 2]
 [3 4]]
B = 
[[5 6]
 [7 8]]


A + B = 
[[ 6  8]
 [10 12]]


### Matrix multiplication

Matrix multiplications combine rows of one matrix with the columns of the other one. Example:

$$A = 
\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}$$

$$B = 
\begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}$$

The product of $A$ with $B$ is:

$$A \cdot B =
\begin{pmatrix}
(1 \cdot 5 + 2 \cdot 7) & (1 \cdot 6 + 2 \cdot 8) \\
(3 \cdot 5 + 4 \cdot 7) & (3 \cdot 6 + 4 \cdot 8)
\end{pmatrix}
=
\begin{pmatrix}
19 & 22 \\
43 & 50
\end{pmatrix}
$$

In python code:

In [4]:
product = np.dot(A, B)
print(f'A = \n{A}')
print(f'B = \n{B}')
print(f'\n AB = \n{product}')

A = 
[[1 2]
 [3 4]]
B = 
[[5 6]
 [7 8]]

 AB = 
[[19 22]
 [43 50]]


### Matrix product by element

In [13]:
product_element = A * B
print(f'A: \n{A}')
print(f'B: \n{B}')
print("\nProduct of A with B element-wise:")
print(product_element)

A: 
[[1 2]
 [3 4]]
B: 
[[5 6]
 [7 8]]

Product of A with B element-wise:
[[ 5 12]
 [21 32]]


### Matrix transpose

The transposition of a matrix exchange its rows with its columns. For example:

$$A = 
\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}$$

$$A^T =
\begin{pmatrix}
1 & 3 \\
2 & 4
\end{pmatrix}


In python code (using NumPy):

In [5]:
At = A.T
print(f'A = \n{A}')
print(f'A^T = \n{At}')

A = 
[[1 2]
 [3 4]]
A^T = 
[[1 3]
 [2 4]]


### Determinant

$$A = 
\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}$$

The determinant of $A$, denoted like $det(A)$, is computed as shown next:

$$det
\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
=
\begin{vmatrix}
1 & 2 \\
3 & 4
\end{vmatrix}
=
(1)(4) - (2)(3) = 4-6 = -2

$$



In NumPy:

In [6]:
determinant = np.linalg.det(A)
print(f'det(A) = {determinant}')

det(A) = -2.0000000000000004


### Matrix inverse

The inverse of a matrix $A$ is denoted as $A^{-1}$ and has the property such that $A \cdot A^{-1} = I$, where $I$ is the identity. In general:

$$ A = 
\begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
$$

$$A^{-1} = 
\frac{1}{det(A)}
\begin{pmatrix}
 d  & -b \\
-c  &  a
\end{pmatrix}
$$

In NumPy can be computed the next way:

In [7]:
inverse = np.linalg.inv(A)
print(f'A = \n{A}\n')
print(f"Inverse of A = \n{inverse}")

A = 
[[1 2]
 [3 4]]

Inverse of A = 
[[-2.   1. ]
 [ 1.5 -0.5]]


### Eigenvectors and eigenvalues

NumPy code:

In [8]:
evals, evecs = np.linalg.eig(A)
print("Eigenvalues of A:\n", evals)
print("Eigenvectors of A:\n", evecs)

Eigenvalues of A:
 [-0.37228132  5.37228132]
Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### Normalize

In [11]:
A_norm = np.linalg.norm(A)
print("\nNorm of A:")
print(A_norm)


Norm of A:
5.477225575051661


### Solution of a linear system equations

In NumPy code:

In [10]:
b= np.array([1, 2])
x = np.linalg.solve(A, b)
print("Solutions to the system Ax = b:\n", x)

print('where:\n')
print(f'A = \n{A}')
print(f'b = \n{b}')

Solutions to the system Ax = b:
 [0.  0.5]
where:

A = 
[[1 2]
 [3 4]]
b = 
[1 2]
