In [25]:
import numpy as np

**Table of contents**<a id='toc0_'></a>    
- 1. [Indexing and Slicing](#toc1_)    
  - 1.1. [Basic Indexing](#toc1_1_)    
    - 1.1.1. [Indexing in 1D arrays](#toc1_1_1_)    
    - 1.1.2. [Indexing in Multidimensional arrays](#toc1_1_2_)    
  - 1.2. [Advanced Indexing](#toc1_2_)    
    - 1.2.1. [Boolean arrays](#toc1_2_1_)    
    - 1.2.2. [Integer array Indexing](#toc1_2_2_)    
  - 1.3. [Basic Slicing](#toc1_3_)    
    - 1.3.1. [Slicing in 1D arrays](#toc1_3_1_)    
    - 1.3.2. [Slicing multidimensional arrays](#toc1_3_2_)    

<!-- vscode-jupyter-toc-config
	numbering=true
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

# 1. <a id='toc1_'></a>[Indexing and Slicing](#toc0_)

 Numpy arrays or *ndarrays* for short, can be indexed using the standard Python syntax: `x[obj]`.

In [26]:
# Example array
arr = np.arange(10, 101, 10)
A = np.random.randint(10, 50, size=(3,3))
print(f'arr = {arr}')
print(f'\nA = \n{A}')

arr = [ 10  20  30  40  50  60  70  80  90 100]

A = 
[[42 21 46]
 [14 48 11]
 [26 28 49]]


## 1.1. <a id='toc1_1_'></a>[Basic Indexing](#toc0_)

### 1.1.1. <a id='toc1_1_1_'></a>[Indexing in 1D arrays](#toc0_)

In [27]:
print(f'arr = {arr}')
print(f'arr[0] = {arr[0]}')
print(f'arr[-1] = {arr[-1]}')
print(f'arr[-2] = {arr[-2]}')

arr = [ 10  20  30  40  50  60  70  80  90 100]
arr[0] = 10
arr[-1] = 100
arr[-2] = 90


### 1.1.2. <a id='toc1_1_2_'></a>[Indexing in Multidimensional arrays](#toc0_)

Get a specific element in an array using its index position.

In [31]:
print(f'A = \n{A}')
print(f'\nA[1,2] = {A[1,2]}')

A = 
[[42 21 46]
 [14 48 11]
 [26 28 49]]

A[1,2] = 11


## 1.2. <a id='toc1_2_'></a>[Advanced Indexing](#toc0_)

More methods and details at the documentation site: [Numpy: Advanced idexing](https://numpy.org/doc/stable/user/basics.indexing.html#advanced-indexing)

### 1.2.1. <a id='toc1_2_1_'></a>[Boolean arrays](#toc0_)

In [28]:
bool_arr = arr % 2 == 0
print(f'arr = {arr}')
print(f'bool_arr = (arr % 2 == 0) ==> {bool_arr}')

arr = [ 10  20  30  40  50  60  70  80  90 100]
bool_arr = (arr % 2 == 0) ==> [ True  True  True  True  True  True  True  True  True  True]


### 1.2.2. <a id='toc1_2_2_'></a>[Integer array Indexing](#toc0_)

The integer array indexing allows the selection of arbitrary items in the array. **Each integer in the array represents the index in the to-be indexed array.**

In [29]:
int_arr = np.arange(0,10,2)
indexed_int_arr = arr[int_arr]
print(f'arr = {arr}')
print(f'int_arr = {int_arr}')
print(f'indexed_new_arr = arr[int_arr] ==> {indexed_int_arr}')

arr = [ 10  20  30  40  50  60  70  80  90 100]
int_arr = [0 2 4 6 8]
indexed_new_arr = arr[int_arr] ==> [10 30 50 70 90]


## 1.3. <a id='toc1_3_'></a>[Basic Slicing](#toc0_)

### 1.3.1. <a id='toc1_3_1_'></a>[Slicing in 1D arrays](#toc0_)

In [30]:
print(f'arr = {arr}')
print(f'arr[1:3] = {arr[1:3]}')
print(f'arr[1:-1] = {arr[1:-1]}')
print(f'arr[1:20] = {arr[1:20]}')
print(f'arr[2:] = {arr[2:]}')

arr = [ 10  20  30  40  50  60  70  80  90 100]
arr[1:3] = [20 30]
arr[1:-1] = [20 30 40 50 60 70 80 90]
arr[1:20] = [ 20  30  40  50  60  70  80  90 100]
arr[2:] = [ 30  40  50  60  70  80  90 100]


### 1.3.2. <a id='toc1_3_2_'></a>[Slicing multidimensional arrays](#toc0_)

In [33]:
print(f'A = \n{A}')
print(f'\nA[:,1:] = \n{A[:,1:]}')

A = 
[[42 21 46]
 [14 48 11]
 [26 28 49]]

A[:,1:] = 
[[21 46]
 [48 11]
 [28 49]]


In [34]:
array = np.random.randint(1, 10, size=(3,3))
print(array)
print(array[0,1])

[[9 4 5]
 [2 5 2]
 [4 5 1]]
4


In [37]:
print(array[:2,:2])

[[9 4]
 [2 5]]
