# Broadcasting

In [2]:
import numpy as np

> The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. 

### General boradcasting rules

Two array dimensions are compatible when:

1. They are equal, or
2. one of them is 1.

### Broadcastable arrays

A set of arrays are called broadcastable if the above rules produce a valid result.

For example, if `a.shape` is (5,1), `b.shape` is (1,6), `c.shape` is (6,) and `d.shape` is () so that d is a scalar, then a, b, c, and d are all broadcastable to dimension (5,6); and

- a acts like a (5,6) array where `a[:,0]` is broadcast to the other columns,
- b acts like a (5,6) array where `b[0,:]` is broadcast to the other rows,
- c acts like a (1,6) array and therefore like a (5,6) array where `c[:]` is broadcast to every row, and finally,
- d acts like a (5,6) array where the single value is repeated.

Here are some more examples that work:

```python
A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  5 x 4
B      (1d array):      4
Result (2d array):  5 x 4

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5
```

And here are some that don't:

```python
A      (1d array):  3
B      (1d array):  4 # trailing dimensions do not match

A      (2d array):      2 x 1
B      (3d array):  8 x 4 x 3 # second from last dimensions mismatched
```

In the next figure, `b` is added to each row of `a`.

![](./media/broadcasting_2.png)

In the next figure, an exception will be raised because of the incompatible shapes

![](https://numpy.org/doc/stable/_images/broadcasting_3.png)

And the last figure, shows how both arrays can stretch if both of them meet the rules.

![](./media/broadcasting_4.png)

### Case 1: n-array vs n-array

NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape, as in the following example:

In [5]:
arr_a = np.array([1,2,3,4])
arr_b = np.array([10,20,30,40])
arr_mult = arr_a * arr_b
print(f'arr_a = {arr_a}')
print(f'arr_b = {arr_b}')
print(f'arr_a * arr_b = {arr_mult}')

arr_a = [1 2 3 4]
arr_b = [10 20 30 40]
arr_a * arr_b = [ 10  40  90 160]


### Case 2: scalar vs n-array

The simplest boradcasting after same size arrays is when a scalar and an array are combined in an operation:

![](./media/broadcasting_1.png)

In [8]:
scalar = 2
print(f'scalar: {scalar}')
print(f'arr_b = {arr_b}')
print(f'scalar * arr_b = {scalar * arr_b}')

scalar: 2
arr_b = [10 20 30 40]
scalar * arr_b = [20 40 60 80]


### Case 3a: n-array vs m-array

In [17]:
arr_c1 =np.array([0.0, 10.0, 20.0])
arr_c2 = arr_c1[:, np.newaxis]
print(f'arr_a = {arr_a}')
print(f'arr_c1 = {arr_c1}')
print(f'arr_c2 = \n{arr_c2}')
print(f'\narr_a + arr_c2 = \n{arr_a + arr_c2}')

arr_a = [1 2 3 4]
arr_c1 = [ 0. 10. 20.]
arr_c2 = 
[[ 0.]
 [10.]
 [20.]]

arr_a + arr_c2 = 
[[ 1.  2.  3.  4.]
 [11. 12. 13. 14.]
 [21. 22. 23. 24.]]


where the method `np.newaxis` adds a new dimension to the array in the given position in order to meet the rules of broadcasting. Otherwise you would raise and exception.

In [14]:
print(f'arr_c1.shape =  {arr_c1.shape}')
print(f'arr_c2.shape = {arr_c2.shape}')

arr_c1.shape =  (3,)
arr_c2.shape = (3, 1)


## Logic operations

### `np.all()`

In [19]:
array = np.array([1,2,3,4,5])
print(np.all(array > 3))

False


### `np.any()`

In [20]:
print(f'array = {array}')
print(np.any(array > 3))

array = [1 2 3 4 5]
True


## Array methods part 2

### Concatenate arrays

In [29]:
print(f'arr_a = {arr_a}')
print(f'arr_b = {arr_b}')
arr_b.dtype
print(f'concatenated array = np.concatenate((arr_a, arr_b)) = {np.concatenate((arr_a, arr_b))}')

arr_a = [1 2 3 4]
arr_b = [10 20 30 40]
concatenated array = np.concatenate((arr_a, arr_b)) = [ 1  2  3  4 10 20 30 40]


### Stack arrays

### Split arrays