In [4]:
import numpy as np

# Array methods and operations in NumPy

Some of the most common methods and operations with arrays using numpy.

In [5]:
arr_a = np.arange(0,11,2)
arr_b = np.array([1,2,3,5,7,11])
print(f'arr_a = {arr_a}')
print(f'arr_b = {arr_b}')

arr_a = [ 0  2  4  6  8 10]
arr_b = [ 1  2  3  5  7 11]


## Concatenation

In [6]:
print(f'arr_a = {arr_a}')
print(f'arr_b = {arr_b}')
arr_b.dtype
print(f'np.concatenate((arr_a, arr_b)) = {np.concatenate((arr_a, arr_b))}')

arr_a = [ 0  2  4  6  8 10]
arr_b = [ 1  2  3  5  7 11]
np.concatenate((arr_a, arr_b)) = [ 0  2  4  6  8 10  1  2  3  5  7 11]


## Stacking arrays

In [7]:
arr_stacked_v = np.vstack((arr_a, arr_b))
arr_stacked_h = np.hstack((arr_a, arr_b))

print(f'arr_a = {arr_a}')
print(f'arr_b = {arr_b}')
print(f'\nnp.vstack((arr_a, arr_b)) = \n{arr_stacked_v}')
print(f'\nnp.hstack((arr_a, arr_b)) = \n{arr_stacked_h}')



arr_a = [ 0  2  4  6  8 10]
arr_b = [ 1  2  3  5  7 11]

np.vstack((arr_a, arr_b)) = 
[[ 0  2  4  6  8 10]
 [ 1  2  3  5  7 11]]

np.hstack((arr_a, arr_b)) = 
[ 0  2  4  6  8 10  1  2  3  5  7 11]


## Split arrays

In order to work with `split` the array must be able to be divided into equal parts, otherwise the method will raise and *error*.

In [8]:
arr_d = np.arange(1,13)
print(f'arr_d = {arr_d}')
print(f'np.split(arr_d,3) = {np.split(arr_d,3)}')

arr_d = [ 1  2  3  4  5  6  7  8  9 10 11 12]
np.split(arr_d,3) = [array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


## Unique

In [9]:
survey_reponses = np.array(["good", "bad", "excelent", "bad", "bad", "excelent", "good", "excelent", "good", "excelent"])

In [10]:
unique_elements, count_elements = np.unique(survey_reponses, return_counts=True)
print(f'unique_elements, count_elements: {unique_elements}, {count_elements}')

NameError: name 'survey_responses' is not defined