In [4]:
import numpy as np

# Array methods and operations in NumPy

Some of the most common methods and operations with arrays using numpy.

In [5]:
arr_a = np.arange(0,11,2)
arr_b = np.array([1,2,3,5,7,11])
print(f'arr_a = {arr_a}')
print(f'arr_b = {arr_b}')

arr_a = [ 0  2  4  6  8 10]
arr_b = [ 1  2  3  5  7 11]


## Concatenation

In [6]:
print(f'arr_a = {arr_a}')
print(f'arr_b = {arr_b}')
arr_b.dtype
print(f'np.concatenate((arr_a, arr_b)) = {np.concatenate((arr_a, arr_b))}')

arr_a = [ 0  2  4  6  8 10]
arr_b = [ 1  2  3  5  7 11]
np.concatenate((arr_a, arr_b)) = [ 0  2  4  6  8 10  1  2  3  5  7 11]


## Stacking arrays

In [7]:
arr_stacked_v = np.vstack((arr_a, arr_b))
arr_stacked_h = np.hstack((arr_a, arr_b))

print(f'arr_a = {arr_a}')
print(f'arr_b = {arr_b}')
print(f'\nnp.vstack((arr_a, arr_b)) = \n{arr_stacked_v}')
print(f'\nnp.hstack((arr_a, arr_b)) = \n{arr_stacked_h}')



arr_a = [ 0  2  4  6  8 10]
arr_b = [ 1  2  3  5  7 11]

np.vstack((arr_a, arr_b)) = 
[[ 0  2  4  6  8 10]
 [ 1  2  3  5  7 11]]

np.hstack((arr_a, arr_b)) = 
[ 0  2  4  6  8 10  1  2  3  5  7 11]


## Split arrays

In order to work with `split` the array must be able to be divided into equal parts, otherwise the method will raise and *error*.

In [8]:
arr_d = np.arange(1,13)
print(f'arr_d = {arr_d}')
print(f'np.split(arr_d,3) = {np.split(arr_d,3)}')

arr_d = [ 1  2  3  4  5  6  7  8  9 10 11 12]
np.split(arr_d,3) = [array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


## Unique

The `unique` functions receives a array and returns a new array where all the elements are unique. Is similar to `set()` functions. In addition to that, te function can return how many times every item was repeated:

- `list_elements, count = unique(list_repeated, return_counts=True)`

In [9]:
survey_reponses = np.array(["good", "bad", "excelent", "bad", "bad", "excelent", "good", "excelent", "good", "excelent"])

In [12]:
unique_elements, count_elements = np.unique(survey_reponses, return_counts=True)
print(f'unique_elements: {unique_elements}')
print(f'count_elements: {count_elements}')

unique_elements: ['bad' 'excelent' 'good']
count_elements: [3 4 3]


## Copy correctly

When copying arrays or array parts to anoter array or variable, you must know array values are passed as **reference** and not as **values**. This means that the value we are "copying" it is actually pointing to the same memory address and is **NOT** creating a new instamce.

In [19]:
arr_x = np.arange(10,20)
arr_y = arr_x[1:3]
print(f'arr_x: {arr_x}')
print(f'arr_y: {arr_y}')
print(20*'-')

arr_x[1:3] = [100, 200]
print(f'arr_x: {arr_x}')
print(f'arr_y: {arr_y}')

arr_x: [10 11 12 13 14 15 16 17 18 19]
arr_y: [11 12]
--------------------
arr_x: [ 10 100 200  13  14  15  16  17  18  19]
arr_y: [100 200]


To avoid the issue in the code above, you can use double brackets or the `.copy()` method. The next 2 examples are equivalent:
- `copy_x = arr_x[[1,2,3]] `
- `copy_x = np.copy(arr_x[1:4])`

In [22]:
arr_x = np.arange(20,30)
# copy_x = arr_x[[1,2,3]]
np.copy(arr_x[1:4])
print(f'arr_x: {arr_x}')
print(f'copy_x: {copy_x}')
print(20*'-')

arr_x[1:3] = [100, 200]
print(f'arr_x: {arr_x}')
print(f'copy_x: {copy_x}')

arr_x: [20 21 22 23 24 25 26 27 28 29]
copy_x: [21 22 23]
--------------------
arr_x: [ 20 100 200  23  24  25  26  27  28  29]
copy_x: [21 22 23]
