In [3]:
import numpy as np

# Array transformations: Reshape and Manipulation

## Reshape

El método `.reshape()` de NumPy permite cambiar la forma de un array sin alterar sus datos. Por ejemplo, si tienes un array `B` de forma `(2, 3)`, puedes cambiarlo a una forma `(3, 2)` utilizando `B.reshape(3, 2)`.

In [7]:
A = np.array([[1,2,3], [4,5,6]])
B = A.reshape(3,2)
a = A.reshape(6)
print(f'A: \n{A}')
print(f'\nA.reshape(3,2): \n{B}')
print(f'\nA.reshape(6): \n{a}')

A: 
[[1 2 3]
 [4 5 6]]

A.reshape(3,2): 
[[1 2]
 [3 4]
 [5 6]]

A.reshape(6): 
[1 2 3 4 5 6]


## Flattened

El método `.flatten()` de NumPy convierte un array multidimensional en un array unidimensional. Esto es útil cuando necesitas trabajar con datos en una forma lineal. Por ejemplo, si tienes un array `D` de forma `(2, 3)`, puedes aplanarlo utilizando `D.flatten()`.

In [9]:
a_flat = A.flatten()
print(f'A: \n{A}')
print(f'\nA.flatten(): {a_flat}')

A: 
[[1 2 3]
 [4 5 6]]

A.flatten(): [1 2 3 4 5 6]


La función ravel también aplanará un array como flatten, pero devuelve una vista del array original cuando sea posible.

In [11]:
A.ravel()

array([1, 2, 3, 4, 5, 6])

## Reverse an array

In [14]:
print(f'A: \n{A}')
print(f'\nA[::-1]: \n{A[::-1]}')

A: 
[[1 2 3]
 [4 5 6]]

A[::-1]: 
[[4 5 6]
 [1 2 3]]
