In [1]:
import numpy as np

# Examples of broadcasting with NumPy

## Example 1:

We have a dataset representing the measurement of the temperature of 7 days in 3 different cities ($3\times7$ array). However, the measurements have a margin of error, and we are given a one-dimensional array with the correction values for each day of the week, with dimensions $1\times7$. To approach the correction in the temperature measurement, instead of duplicating the correction array for each city (row), we apply broadcasting:

In [4]:
# Temperatures (3 cities, 7 days)
temperatures = np.array([
    [30, 32, 31, 29, 28, 27, 26],
    [25, 24, 22, 23, 26, 27, 28],
    [20, 21, 19, 18, 17, 16, 15]
])

# Correction (1 value per day)
correction = np.array([1, -1, 0.5, -0.5, 0, 1, -1])

# Apply the correction using broadcasting
temps_fixed = temperatures + correction

print(f'Original temperatures: \n{temperatures}')
print(f'\nCorrection values: {correction}')
print(f'\nFixed temperatures: \n{temps_fixed}')

Original temperatures: 
[[30 32 31 29 28 27 26]
 [25 24 22 23 26 27 28]
 [20 21 19 18 17 16 15]]

Correction values: [ 1.  -1.   0.5 -0.5  0.   1.  -1. ]

Fixed temperatures: 
[[31.  31.  31.5 28.5 28.  28.  25. ]
 [26.  23.  22.5 22.5 26.  28.  27. ]
 [21.  20.  19.5 17.5 17.  17.  14. ]]


How broadcasting was applied:

![](./media/Numpy_broadcasting.jpg)

## Example 2:

We have a $3\times3$ matrix representing the sales values of 3 products in 3 different stores and a $3\times1$ vector containing a sales bonus to be applied per store. The broadcasting allows to add this bonus in a more efficient way to each matrix row.

In [7]:
# Product sales in 3 different stores
sales = np.array([
  [100, 200, 300],
  [400, 500, 600],
  [700, 800, 900]
])

# Sales bonus per store
bonus = np.array([
  [10],
  [20],
  [30]
])

sales_updated = sales + bonus

print(f'Sales: \n{sales}')
print(f'\nSales with bonus:\n {sales_updated}')

Sales: 
[[100 200 300]
 [400 500 600]
 [700 800 900]]

Sales with bonus:
 [[110 210 310]
 [420 520 620]
 [730 830 930]]


In this example, numpy expands the array horizontally (ading the lacking columns), the next image shows it more visually:

![](./media/broadcasting_ex2.jpg)