# NumPy: Practical exercises

Exercises with NumPy, designed to strength the knowledge about the most used methods and be prepared for the future conections with **Pandas** and **Matplotlib**.

## Basic Operations with Arrays

>Create 2 1-dimensional arrays with integers and complete the *sum*, *substraction*, *multiplication*, and *division*.

In [5]:
import numpy as np

array1 = np.array([10, 20, 30, 40])
array2 = np.array([1, 2, 3, 4])

sum = array1 + array2
substraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print(f'array1: {array1}')
print(f'array2: {array2}')
print(20*"-")
print("Sum:", sum)
print("Substraction:", substraction)
print("Multiplication:", multiplication)
print("Division:", division)

array1: [10 20 30 40]
array2: [1 2 3 4]
--------------------
Sum: [11 22 33 44]
Substraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]


## Statistics with Arrays

Given an array with data, calculates the average, the median, the variance, and the standar deviation.

In [6]:
data = np.array([23, 76, 35, 67, 89, 45, 68, 79, 35])

average = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_deviation = np.std(data)

print(f'data: {data}')
print(20*"-")
print("Average:", average)
print("Median:", median)
print("Variance:", variance)
print("Standar deviation:", std_deviation)

data: [23 76 35 67 89 45 68 79 35]
--------------------
Average: 57.44444444444444
Median: 67.0
Variance: 484.02469135802465
Standar deviation: 22.000561160071


## Matrix Operations

Create 2 2-by-2 matrices and performs the operations of addition, substraction, multiplication (matrix product) and the inverse. 

In [8]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

suma_matrices = matrix1 + matrix2
resta_matrices = matrix1 - matrix2
producto_matrices = np.dot(matrix1, matrix2)
inversa_matriz1 = np.linalg.inv(matrix1)

print(f'matrix1: \n{matrix1}')
print(f'\nmatrix2: \n{matrix2}')
print(20*"-")
print("Suma de matrices:\n", suma_matrices)
print("Resta de matrices:\n", resta_matrices)
print("Producto de matrices:\n", producto_matrices)
print("Inversa de la matriz 1:\n", inversa_matriz1)

matrix1: 
[[1 2]
 [3 4]]

matrix2: 
[[5 6]
 [7 8]]
--------------------
Suma de matrices:
 [[ 6  8]
 [10 12]]
Resta de matrices:
 [[-4 -4]
 [-4 -4]]
Producto de matrices:
 [[19 22]
 [43 50]]
Inversa de la matriz 1:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## Solving a System of Linear Equations

Solve the next system of linear equations given by $Ax=b$, where A is a 2-by-2 matrix and $b$ is a 2-elements vector.

In [13]:
A = np.array([[2, 3], [1, 2]])
b = np.array([8, 5])

x = np.linalg.solve(A, b)

print(f'A: \n{A}')
print(f'\nb: \n{b}')
print("\nSolution -> x =", x)

A: 
[[2 3]
 [1 2]]

b: 
[8 5]

Solution -> x = [1. 2.]


## Data Simulation

Generate an array with 1000 random numbers with a normal distribution with a mean of 0 and a standar deviation of 1. Calculate the media and the standar deviation of the generated array.

In [14]:
datos_simulados = np.random.normal(0, 1, 1000)
media_simulada = np.mean(datos_simulados)
desviacion_simulada = np.std(datos_simulados)

print("Media de los datos simulados:", media_simulada)
print("Desviación estándar de los datos simulados:", desviacion_simulada)

Media de los datos simulados: -0.05306759063150912
Desviación estándar de los datos simulados: 0.9858721655048418
